name: 📑 Add Source
description: Add Sources to help other to improve their Coding Skills.
labels: ["🛠 goal: fix"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: Please add link of the source
    validations:
      required: true
